### PR TITLE
remove unused res

### PR DESCRIPTION
**Pull request by Horki**
@PolyMeilex Hi, just a quick fix of unues var `res`

### CODE REVIEW

**Comment by Be-ing** [comment]
This breaks the build without `gtk3` because `res` is referenced in the `println!`. An alternative solution could be wrapping the `let` line and the `println!` in a block guarded by the `#[cfg]`.

**Comment by PolyMeilex** [comment]
Hi!
Let's just wrap the whole thing in a block and put cfg on top of that

**Comment by Be-ing** [comment]
This does not build:
```
rfd on  quickfix_example_msg [$?] is 📦 v0.7.0 via 🦀 v1.58.1 took 3s 
❯ cargo run --no-default-features --features parent --example msg
   Compiling rfd v0.7.0 (/home/be/sw/rfd)
error[E0433]: failed to resolve: could not find `MessageDialog` in `rfd`
  --> examples/msg.rs:16:24
   |
16 |         let res = rfd::MessageDialog::new()
   |                        ^^^^^^^^^^^^^ could not find `MessageDialog` in `rfd`

error[E0433]: failed to resolve: could not find `MessageButtons` in `rfd`
  --> examples/msg.rs:19:31
   |
19 |             .set_buttons(rfd::MessageButtons::OkCancel)
   |                               ^^^^^^^^^^^^^^ could not find `MessageButtons` in `rfd`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `rfd` due to 2 previous errors
```

I think the `cfg!` is done at runtime? Try `#[cfg]` instead.

**Review by Be-ing — APPROVED** [review]

**Comment by Be-ing** [comment]
Works on my machine.

**Review by PolyMeilex — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
