### PR TITLE
deps: Update ashpd to 0.10

### PR DESCRIPTION
**Pull request by torokati44**
Similar to https://github.com/PolyMeilex/rfd/pull/212, to avoid duplicating `ashpd` in https://github.com/ruffle-rs/ruffle/pull/18468.

The `Cargo.lock` diff here also looks neat IMHO.

### CODE REVIEW

**Comment by PolyMeilex** [comment]
Thanks, and sorry for the delay.

**Comment by torokati44** [comment]
No worries, and thank you! 
Is there a timeline for the next release with this in it?

**Comment by PolyMeilex** [comment]
Sure, it should be up as 0.15.1 already

**Comment by torokati44** [comment]
Awesome! 🥳

**Pull request merged**
