### PR TITLE
Update gtk to 0.16

### PR DESCRIPTION
**Pull request by wusyong**
We are upgrading to gtk 0.16. Could this crate also bump a version for it?

### CODE REVIEW

**Comment by PolyMeilex** [comment]
Sure thing, thanks!

**Comment by wusyong** [comment]
Thanks for merging it! Could you publish a version when you have time? We want to publish a release too this week.

**Comment by PolyMeilex** [comment]
> Thanks for merging it! Could you publish a version when you have time? We want to publish a release too this week.

That was done yesterday already 😉

**Comment by wusyong** [comment]
Oh sorry I didn't check again. Thank you so much!

**Comment by wusyong** [comment]
@PolyMeilex Sorry to bother you again. But bumping gtk and windows version will increase MSRV. It should be a minor bump at least.
Could you yank 0.10.1 and bump with a minor release?

**Comment by PolyMeilex** [comment]
No problem, you are right, 0.10.1 yanked, 0.11.0 released

**Comment by PolyMeilex** [comment]
@wusyong btw do you know what's the current MSRV? I know that windows-rs 0.43 bumped us up to 1.64, but after that I lost track, I'd like to plop the MSRV into Cargo.toml and enforce it in CI build as well.

**Comment by lucasfernog** [comment]
I believe it's 1.64.

**Pull request merged**
