### PR TITLE
xdg-desktop-portal: Bump to new ashpd stuff

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Marked as WIP until we get all of the new stuff in a new release. Hopefully soon-ish

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for going out of your way to help downstream!

**Comment by bilelmoussaoui** [comment]
This one should be ready for a review now, we are getting closer to a stable release from ashpd side.

**Comment by bilelmoussaoui** [comment]
Should be good to go now :)

**Review by PolyMeilex — APPROVED** [review]
LGTM

**Comment by PolyMeilex** [comment]
Thanks!

**Pull request merged**
