### PR TITLE
macos parent for sync FileDialog

### PR DESCRIPTION
**Pull request by m11m**
I don't claim to know what I am doing, but here is something that worked for me. :)

Note: It does not result in the "sheet" behavior, but it does result in the "child window" behavior.

### CODE REVIEW

**Comment by m11m** [comment]
re: https://github.com/PolyMeilex/rfd/issues/53

**Comment by PolyMeilex** [comment]
Looks promising, does it produce child always on top of parent behavior?

**Comment by m11m** [comment]
I observe it working similarly to how it works without setting the child, except that when you move the parent window, the child moves along with it as a window group.

**Comment by PolyMeilex** [comment]
It's a good middle ground, sheet forces us to start an event loop, so I would like to avoid that in sync API if possible.

**Pull request merged**
