### PR TITLE
feat(macos): add `set_can_create_directories`

### PR DESCRIPTION
**Pull request by amrbashir**
ref: https://github.com/tauri-apps/plugins-workspace/issues/949

### CODE REVIEW

**Comment by PolyMeilex** [comment]
Are there any disadvantages to just always enabling it, and not exposing it in public API?

**Comment by amrbashir** [comment]
Not that I know of but seeing that electron decided to provide an explicit option for it, and from experience in Tauri, users always ask for the option.

I think we can enable it by default and come back to an API if more users ask for it?

**Comment by PolyMeilex** [comment]
Now that I look at the linked issue, it seems like it is referring to directory picker, but tauri is stuck on old rfd version that used to not enable create-dir for those.

Perhaps I can just do a backport release for the version tauri uses, so it can pin to that instead and get the new directory picker behavior on macos?

---
Would be great to just switch from problematic gtk based rfd to xdg-portal based rfd in tauri and allow it to update to new versions, but that will probably flood the issue tracker with people that don't want to have xdg-portal on their systems (don't ask why some people don't want to have a core system component installed, that's how life on Linux looks like at times XD)

**Comment by amrbashir** [comment]
> Now that I look at the linked issue, it seems like it is referring to directory picker, but tauri is stuck on old rfd version that used to not enable create-dir for those.

I think creating directories should still be enabled for file dialogs specially in the save dialog.

> Perhaps I can just do a backport release for the version tauri uses, so it can pin to that instead and get the new directory picker behavior on macos?

That would be really nice, thanks.

> Would be great to just switch from problematic gtk based rfd to xdg-portal based rfd in tauri and allow it to update to new versions, but that will probably flood the issue tracker with people that don't want to have xdg-portal on their systems (don't ask why some people don't want to have a core system component installed, that's how life on Linux looks like at times XD)

I can relate to the pain, developers simply don't want to require their users to have certain dependency installed. Linux users can be masochistic when it comes to reducing the number of packages on their system.

**Comment by PolyMeilex** [comment]
I don't mind the additional API afterall, let's merge this as is.

I will ping you once I do the backport release. We really have to figure something out long term tho :smile:

**Comment by amrbashir** [comment]
> macOs does that by default for save dialogs

good to know, don't have a macOS to test 😄

> I will ping you once I do the backport release. We really have to figure something out long term tho 😄

yeah, it is something we will need to do before tauri v2 goes into stable

**Comment by PolyMeilex** [comment]
Decided to just drop the idea of doing backports, I've added zenity fallback for xdg portal backend instead, for people with broken systems.

XDG Portal backend is now the default, and GTK3 became opt-in (and will probably be remove in the future)

This is now published as 0.14.0, and tauri should be able to switch to it.

**Pull request merged**
